" GUI options
set lines=58
set columns=220
set guioptions -=m 
set guioptions -=T
"set guifont=Source\ Code\ Pro\ for\ Powerline\ Semi-Bold\ 9

set guifont=SauceCodePro\ Nerd\ Font\ Mono\ Semi-Bold\ 9
"set guifont=SauceCodePro\ Nerd\ Font\ Mono\ Semi-Bold\ 10

"colorscheme solarized8
"set background=light
set background=dark

